services:
  - type: web
    name: new-faq-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    envVars:
      - key: MESOLITICA_API_KEY
        sync: false